name: 'data_job_vacancy_insight'
version: '1.0.0'
config-version: 2

profile: 'datawarehouse_job_vacancy_insight'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  datawarehouse:
    +profile: 'datawarehouse_job_vacancy_insight'
    +schema: 'modeling_data'
  datamart:
    +profile: 'datamart_job_vacancy_insight'
    reporting:
      +schema: 'reporting_data'
    model_training:
      +schema: 'training_data'
