name: 'data_job_vacancy_insight'
version: '1.0.0'
config-version: 2

profile: 'data_job_vacancy_insight' # using to find profiles.yml(file with settings configuration with dababase)

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  data_job_vacancy_insight:

