data_job_vacancy_insight:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: datawarehouse  
      port: 5432
      user: IsaacLee
      pass: job_vacancy_insight
      dbname: job_vacancy_insight_datawarehouse
      schema: staging_data  

    prod:
      type: postgres
      threads: 1
      host: datamart  
      port: 5433
      user: IsaacLee
      pass: job_vacancy_insight
      dbname: job_vacancy_insight_datamart
      schema: modeling_data
