data_job_vacancy_insight:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost  
      port: 5432  
      user: IsaacLee  
      pass: job_vacancy_insight  
      dbname: job_vacancy_insight_datawarehouse 
      schema: staging_data  