version: 2

sources:
  - name: staging_data
    database: job_vacancy_insight_datawarehouse
    schema: staging_data
    tables:
      - name: job_listings_104

  - name: modeling_data
    database: job_vacancy_insight_datawarehouse
    schema: modeling_data
    tables:
      - name: er_company
      - name: er_job_type
      - name: er_tools
      - name: er_major