# define source data and generic test for er model
version: 2

sources:
  - name: staging_data
    database: job_vacancy_insight_datawarehouse
    schema: staging_data
    description: "This schema contains raw data from external job listing sources."
    tables:
      - name: job_listings_104
        description: "Raw job listings data collected from the 104 job platform."
        tests:
          - unique:
              column_name: unique_col
          - not_null:
              column_name: unique_col

  - name: modeling_data
    database: job_vacancy_insight_datawarehouse
    schema: modeling_data
    description: "This schema contains transformed and structured data for analytical purposes."
    tables:
      - name: er_job
        description: "Stores job details including references to company, job types, degrees, majors, and tools."
        columns:
          - name: unique_id
            tests:
              - unique
              - not_null
          - name: data_role
            tests:
                - accepted_values:
                    values: ['Data Analyst', 'Data Scientist', 'Data Engineer', 'Machine Learning Engineer', 'Business Analyst', 'Data Architect', 'BI Engineer']
                - not_null
          - name: company_id
            tests:
              - not_null
              - relationships:
                  to: ref('er_company')
                  field: company_id
          - name: job_types
            tests:
              - not_null
          - name: degree
            tests:
              - not_null
          - name: crawl_date
            tests:
              - not_null

      - name: er_company
        description: "Contains company details."
        columns:
          - name: company_id
            tests:
              - unique
              - not_null

      - name: er_company_location
        description: "Details of company locations."
        columns:
          - name: company_id
            tests:
              - not_null
              - relationships:
                  to: ref('er_company')
                  field: company_id
          - name: county_id
            tests:
              - not_null
              - relationships:
                  to: ref('er_county')
                  field: county_id
          - name: district_id
            tests:
              - not_null

      - name: er_tools
        description: "Tools mentioned in job listings."
        columns:
          - name: tool_id
            tests:
              - unique
              - not_null

      - name: er_major
        description: "Academic majors mentioned in job listings."
        columns:
          - name: major_id
            tests:
              - unique
              - not_null

      - name: er_job_type
        description: "Types of jobs listed."
        columns:
          - name: job_type_id
            tests:
              - unique
              - not_null

      - name: er_degree
        description: "Degrees mentioned in job listings."
        columns:
          - name: degree_id
            tests:
              - unique
              - not_null