version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: job_vacancy_insight
      POSTGRES_USER: IsaacLee
      POSTGRES_PASSWORD: job_vacancy_insight
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
